### ISSUE TITLE
Dap-Ruby debugger fails, extension moved debug module

### ISSUE THREAD

**Issue by hatch-carl** [emacs-lsp/dap-mode#206]
```
Error: Cannot find module '/Users/carl/.emacs.d/.extension/vscode/rebornix.Ruby/extension/out/debugger/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
It appears that the extension author moved main file from `.../out/debugger/main.js` to `../dist/debugger/main.js`

**Comment by yyoncho** [comment]
Is changing dap-ruby-debug-program sufficient?

**Comment by seagle0128** [comment]
Same issue here.

`~/.emacs.d/.extension/vscode/rebornix.Ruby/extension/out/debugger/main.js` should be `/.emacs.d/.extension/vscode/rebornix.Ruby/extension/dist/debugger/main.js` now.

**Comment by helpotters** [comment]
Has it been updated again? I think it's under .local now.
