### ISSUE TITLE
lldb-vscode 0.2.2 not working for basic C++ example?

### ISSUE THREAD

**Issue by roangel** [emacs-lsp/dap-mode#375]
Hi all,

I am trying to install and setup `dap-mode` for C++. For that, I downloaded the extension `lldb-vscode` directly from the extension manager of vscode, located in `~/.vscode/extensions/lanza.lldb-vscode-0.2.2/bin/darwin/bin/lldb-vscode`, added this to my config file: 
```
(setq dap-lldb-debug-program "~/.vscode/extensions/lanza.lldb-vscode-0.2.2/bin/darwin/bin/lldb-vscode")
(require 'dap-lldb)
```

And tried to run `dap-debug` on a really simple `main.cpp` file:

```
int main() {
	int a = 1;
	int b = 2;
	int c = a + b;
	return 0;
}
```

However the emacs outputs this error: (wrong-type-argument stringp nil).

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  make-process(:name "LLDB::Run" :connection-type pipe :coding no-conversion :command "~/.vscode/extensions/lanza.lldb-vscode-0.2.2/bin/darwin/bin/lldb-vscode" :stderr "*LLDB::Run stderr*" :noquery t)
  dap--create-session((:type "lldb" :cwd "/home/angel/src/cpp_examples/" :request "launch" :program "/home/angel/src/cpp_examples/main.cpp" :name "LLDB::Run" :dap-server-path "~/.vscode/extensions/lanza.lldb-vscode-0.2.2/bin/darwin/bin/lldb-vscode"))
  dap-start-debugging((:type "lldb" :cwd "/home/angel/src/cpp_examples/" :request "launch" :program "/home/angel/src/cpp_examples/main.cpp" :name "LLDB::Run" :dap-server-path "~/.vscode/extensions/lanza.lldb-vscode-0.2.2/bin/darwin/bin/lldb-vscode"))
  dap-debug((:type "lldb" :cwd "/home/angel/src/cpp_examples/" :request "launch" :program "/home/angel/src/cpp_examples/main.cpp" :name "LLDB::Run" :dap-server-path "~/.vscode/extensions/lanza.lldb-vscode-0.2.2/bin/d..."))
  funcall-interactively(dap-debug (:type "lldb" :cwd "/home/angel/src/cpp_examples/" :request "launch" :program "/home/angel/src/cpp_examples/main.cpp" :name "LLDB::Run" :dap-server-path "~/.vscode/extensions/lanza.lldb-vscode-0.2.2/bin/d..."))
  call-interactively(dap-debug record nil)
  command-execute(dap-debug record)
  helm-M-x-execute-command(dap-debug)
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal((((name . "Emacs Commands history") (candidates . #f(compiled-function () #<bytecode 0x155ab72a27d1>)) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . delete-backward-char) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x155ab6bc3ac1>)) (f1 lambda nil ... ...) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort helm-fuzzy-highlight-matches) (volatile) (match . identity) (redisplay . identity) (nomark) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (must-match) (group . helm-command) (match-dynamic)) ((name . "Emacs Commands") (candidates . #f(compiled-function () #<bytecode 0x155ab6ecc179>)) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . delete-backward-char) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x155ab6bc3ac1>)) (f1 lambda nil ... ...) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort helm-fuzzy-highlight-matches) (volatile) (match . identity) (redisplay . identity) (nomark) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (must-match) (group . helm-command) (match-dynamic))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history)
  apply(helm-internal ((((name . "Emacs Commands history") (candidates . #f(compiled-function () #<bytecode 0x155ab72a27d1>)) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . delete-backward-char) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x155ab6bc3ac1>)) (f1 lambda nil ... ...) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (24 keymap ... ... ... ... ... ... ... ... ... ... ... ...) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark-forward) (0 . helm-toggle-visible-mark) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort helm-fuzzy-highlight-matches) (volatile) (match . identity) (redisplay . identity) (nomark) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keeping se...") (must-match) (group . helm-command) (match-dynamic)) ((name . "Emacs Commands") (candidates . #f(compiled-function () #<bytecode 0x155ab6ecc179>)) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . delete-backward-char) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x155ab6bc3ac1>)) (f1 lambda nil ... ...) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (24 keymap ... ... ... ... ... ... ... ... ... ... ... ...) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark-forward) (0 . helm-toggle-visible-mark) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort helm-fuzzy-highlight-matches) (volatile) (match . identity) (redisplay . identity) (nomark) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keeping se...") (must-match) (group . helm-command) (match-dynamic))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history))
  helm((((name . "Emacs Commands history") (candidates . #f(compiled-function () #<bytecode 0x155ab72a27d1>)) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . delete-backward-char) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x155ab6bc3ac1>)) (f1 lambda nil ... ...) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort helm-fuzzy-highlight-matches) (volatile) (match . identity) (redisplay . identity) (nomark) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (must-match) (group . helm-command) (match-dynamic)) ((name . "Emacs Commands") (candidates . #f(compiled-function () #<bytecode 0x155ab6ecc179>)) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . delete-backward-char) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x155ab6bc3ac1>)) (f1 lambda nil ... ...) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort helm-fuzzy-highlight-matches) (volatile) (match . identity) (redisplay . identity) (nomark) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (must-match) (group . helm-command) (match-dynamic))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history)
  apply(helm ((((name . "Emacs Commands history") (candidates . #f(compiled-function () #<bytecode 0x155ab72a27d1>)) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . delete-backward-char) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x155ab6bc3ac1>)) (f1 lambda nil ... ...) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (24 keymap ... ... ... ... ... ... ... ... ... ... ... ...) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark-forward) (0 . helm-toggle-visible-mark) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort helm-fuzzy-highlight-matches) (volatile) (match . identity) (redisplay . identity) (nomark) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keeping se...") (must-match) (group . helm-command) (match-dynamic)) ((name . "Emacs Commands") (candidates . #f(compiled-function () #<bytecode 0x155ab6ecc179>)) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . delete-backward-char) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x155ab6bc3ac1>)) (f1 lambda nil ... ...) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (24 keymap ... ... ... ... ... ... ... ... ... ... ... ...) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark-forward) (0 . helm-toggle-visible-mark) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort helm-fuzzy-highlight-matches) (volatile) (match . identity) (redisplay . identity) (nomark) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keeping se...") (must-match) (group . helm-command) (match-dynamic))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history))
  helm(:sources (((name . "Emacs Commands history") (candidates . #f(compiled-function () #<bytecode 0x155ab72a27d1>)) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . delete-backward-char) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x155ab6bc3ac1>)) (f1 lambda nil ... ...) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort helm-fuzzy-highlight-matches) (volatile) (match . identity) (redisplay . identity) (nomark) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (must-match) (group . helm-command) (match-dynamic)) ((name . "Emacs Commands") (candidates . #f(compiled-function () #<bytecode 0x155ab6ecc179>)) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . delete-backward-char) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x155ab6bc3ac1>)) (f1 lambda nil ... ...) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort helm-fuzzy-highlight-matches) (volatile) (match . identity) (redisplay . identity) (nomark) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (must-match) (group . helm-command) (match-dynamic))) :prompt "M-x " :buffer "*helm M-x*" :history helm-M-x-input-history)
  helm-M-x-read-extended-command([## helm-ff-avfs-directory ansi-color-apply-overlay-face isearch--state-pop-fun--cmacro locals dap-ui-breakpoint-log-message -is-infix\? vc-git-stash-snapshot gdb-script-syntax-propertize-function edebug-trace image-dired-update-property enriched-annotation-format treemacs-project->path-status lsp-make-formatting-capabilities lsp-folding-range-limit posframe--insert-string :filterText dired-backup-diff electric-help-orig-major-mode ido-choice-list _message resourceOperations gdb-frame-locals-buffer avl-tree--stack-store--cmacro cl-print--preprocess Find\ file\ in\ directory selinux-context edebug-clear-frequency-count -some\? vc-git-conflicted-files 0 anaconda-mode-running-p :tooltip being Load\ snippets\.\.\. f-directory\? Edebug\ All\ Defs time-format helm-source-info-ess-defs \' tramp-rename-files helm-grep-mode-jump-other-window-forward lsp--virtual-buffer-mappings org-babel-results-keyword treemacs--follow-after-buffer-list-update dont-create treemacs--follow-tag-at-point helm-buffers--get-tab-from-name cl-structure-object projectile-tags-file-name ...])
  helm-M-x(nil)
  funcall-interactively(helm-M-x nil)
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

**Comment by yyoncho** [comment]
Note that you are supposed to pass a list:

```
dap-gdb-lldb-debug-program is a variable defined in ‘dap-gdb-lldb.el’.
Its value is
("node" "/home/yyoncho/.emacs.d/.extension/vscode/webfreak.debug/extension/out/src/gdb.js")

  This variable may be risky if used as a file-local variable.
  You can customize this variable.

Documentation:
The path to the LLDB debugger.
```

**Comment by roangel** [comment]
Thanks @yyoncho ! That was effectively my problem, that I didn't pass the variable right. However, it was for `dap-llbd` extension of dap-mode, and not for `dap-gdb-llbd`. In any case, couldn't get `dap-llbd` working ultimately because these files (https://github.com/lanza/lldb-vscode/tree/master/bin/darwin/bin) are compiled for MAC. So I switched to `code-debug`, from webfreak (https://github.com/WebFreak001/code-debug). I cloned the repository and tried this configuration:

```
(setq dap-gdb-lldb-debug-program `("node", "/home/angel/src/code-debug/src/gdb.ts"))
(require 'dap-gdb-lldb)
```

Still getting this error when trying to run `dap-debug` in the same example as before:
`helm-M-x-execute-command: Searching for program: No such file or directory, node`

Any idea why this might be happening? Thanks

**Comment by yyoncho** [comment]
> helm-M-x-execute-command: Searching for program: No such file or directory, nodе

Do you have nodejs on your system?

**Comment by roangel** [comment]
Aha, ok, yes, that was it. However, I get this error now:
```
/home/angel/src/code-debug/src/gdb.ts:1
(function (exports, require, module, __filename, __dirname) { import { MI2DebugSession } from './mibase';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

Process GDB::Run stderr finished
```

Do I need a different version of nodejs?

**Comment by yyoncho** [comment]
most likely yes. I am not following each adapter development so I cannot provide details on that.

**Comment by roangel** [comment]
> Aha, ok, yes, that was it. However, I get this error now:
> 
> ```
> /home/angel/src/code-debug/src/gdb.ts:1
> (function (exports, require, module, __filename, __dirname) { import { MI2DebugSession } from './mibase';
>                                                               ^^^^^^
> 
> SyntaxError: Unexpected token import
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:616:28)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:188:16)
>     at bootstrap_node.js:609:3
> 
> Process GDB::Run stderr finished
> ```
> 
> Do I need a different version of nodejs?

solved this by using the version of gdb.js that comes along with executing `dap-gdb-lldb-setup`, instead of the version in the last master in the webfreak repository.
