### ISSUE TITLE
Error shows "Cannot evaluate, please specify projectName in launch.json" when trying to attach debug Java

### ISSUE THREAD

**Issue by xqliu** [emacs-lsp/dap-mode#46]
When trying to attach java debug to running springboot process, it successes, and break point is hit, program also stops on the breakpoint line.

But when trying to evaluate an variable or do other debug command,  exception like below shows up:

The below exception was thrown when trying to evaluate a local variable

Exception as below:

```
Cannot evalution expression because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
com.microsoft.java.debug.core.DebugException: Cannot evalution expression because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.\
json..
  at com.microsoft.java.debug.core.adapter.AdapterUtils.createCompletionException(AdapterUtils.java:227)
  at com.microsoft.java.debug.core.adapter.handler.EvaluateRequestHandler.lambda$handle$0(EvaluateRequestHandler.java:103)
  at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
  at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json.
  at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.findJavaProjectByStackFrame(JdtEvaluationProvider.java:231)
  at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.ensureDebugTarget(JdtEvaluationProvider.java:311)
  at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.evaluate(JdtEvaluationProvider.java:111)
  at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.evaluate(JdtEvaluationProvider.java:105)
  at com.microsoft.java.debug.core.adapter.handler.EvaluateRequestHandler.lambda$handle$0(EvaluateRequestHandler.java:76)
  ... 6 more
```

Expect:  can evaluate variables successfully.

**Comment by xqliu** [comment]
Might related to follow issue

https://github.com/Microsoft/java-debug/pull/146
https://github.com/Microsoft/vscode-java-test/issues/102

**Comment by yyoncho** [comment]
@xqliu I am aware of that issue - you may workaround it by using dap-debug-edit-template and then specify the projectName. The only issue is that the template is populated with some stuff which have to be cleaned up if you want to reuse the command and it has to be executed from the java file. I will come up with more natural solution. Also, we may try to upgrade to the latest debug adapter and check whether this is fixed in  the adapter.

**Comment by yyoncho** [comment]
The following code might act as a workaround for the issue. We will work more extending `dap-debug-edit-template` to make the flow easier. I will close the issue with workaround label, please reopen if it does not work. 
```
(with-current-buffer "{replace with the java-file-name}"
(dap-debug
 `(
   :type "java"
   :request "attach"
   :hostName "localhost"
   :projectName "{replace with projectName}"))
```
