### ISSUE TITLE
unable to  debug java project

### ISSUE THREAD

**Issue by serezlan** [emacs-lsp/dap-mode#466]
Hello,

I've been enjoying using lsp+dap for a few months now.
This afternoon I fired up my emacs and for some reason it cannot debug my project. It failed with following message appears on "Warning" buffer

Warning (emacs): Initialize request failed: 'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'

I've been trying a few things below:
- Reinstall eclipse-jdt-ls
- - remove workspace folder 
- - updating lsp and dap 
- - Trying on freshly created maven project

Unfortunately nothing works. 

My system:
- Debian 10
- - openJDK 11
- emacs 27.1
- 
Here's output from lsp-log:

 Apr 26, 2021, 6:21:32 PM [error response][launch]: 'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'
'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'
java.lang.NoSuchMethodError: 'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'
	at com.microsoft.java.debug.plugin.internal.AdvancedLaunchingConnector$AdvancedStringArgumentImpl.<init>(AdvancedLaunchingConnector.java:124)
	at com.microsoft.java.debug.plugin.internal.AdvancedLaunchingConnector.defaultArguments(AdvancedLaunchingConnector.java:47)
	at com.microsoft.java.debug.core.DebugUtility.launch(DebugUtility.java:205)
	at com.microsoft.java.debug.core.DebugUtility.launch(DebugUtility.java:97)
	at com.microsoft.java.debug.core.adapter.handler.LaunchWithDebuggingDelegate.launch(LaunchWithDebuggingDelegate.java:180)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.launch(LaunchRequestHandler.java:242)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handleLaunchCommand(LaunchRequestHandler.java:142)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handle(LaunchRequestHandler.java:81)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:87)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:86)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Please advice. Thank you.

**Comment by yyoncho** [comment]
`(setq lsp-java-jdt-download-url  "https://download.eclipse.org/jdtls/milestones/1.0.0/jdt-language-server-1.0.0-202104151857.tar.gz")`

+ deleting jdtls installation  ~/.emacs.d/.cache/lsp/ + reinstall should fix the issue. I will pin jdtls to use older version of the server

**Comment by serezlan** [comment]
@yyoncho  Thanks. It works.
