### ISSUE TITLE
dap-lldb: Wrong type argument

### ISSUE THREAD

**Issue by tastytea** [emacs-lsp/dap-mode#483]
I'm trying to debug with `lldb-vscode`, but all I get is `if: Wrong type argument: stringp, nil` in the \*Messages\* buffer after running `dap-debug` . When I run `dap-debug` with my real config (not the minimal init.el from below), I get `apply: Wrong type argument: stringp, nil`.

### Configuration

GNU Emacs 27.2, all packages freshly upgraded to the newest VCS versions.
lldb version 12.0.0 (was the same with 11)
OS: Gentoo Linux

#### Minimal init.el

``` elisp
;; Bootstrap straight.
(customize-set-variable 'straight-repository-branch "master")
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el"
                         user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(require 'straight)

(straight-use-package 'dap-mode)
(customize-set-variable 'dap-lldb-debug-program "/usr/bin/lldb-vscode")
(require 'dap-lldb)
```

#### launch.json

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug with lldb",
            "type": "lldb-vscode",
            "request": "launch",
            "program": "${workspaceFolder}/build/src/epubgrep",
            "args": ["test", "tests/test.epub3"],
            "cwd": "${workspaceFolder}",
            "environment": [],
            "stopAtEntry": false,
            "externalConsole": true,
            "MIMode": "lldb"
        }
    ]
}

```

**Comment by tastytea** [comment]
Here is a minimal C++-project to reproduce the issue: [daptest.tar.gz](https://github.com/emacs-lsp/dap-mode/files/6759183/daptest.tar.gz). Run `cmake -S . -B build` followed by `cmake --build build` and then `M-x dap-debug`.

**Comment by myrgy** [comment]
Hi guys. I have similar issue with gdb  (doom-emacs/Linux)

```
TypeError: Cannot read property '1' of null
    at Object.parseMI (/home/user/.emacs.d/.local/etc/dap-extension/vscode/webfreak.debug/extension/out/src/backend/mi_parse.js:262:46)
    at /home/user/.emacs.d/.local/etc/dap-extension/vscode/webfreak.debug/extension/out/src/backend/mi2/mi2.js:327:43
    at Array.forEach (<anonymous>)
    at MI2.onOutput (/home/user/.emacs.d/.local/etc/dap-extension/vscode/webfreak.debug/extension/out/src/backend/mi2/mi2.js:321:15)
    at MI2.stdout (/home/user/.emacs.d/.local/etc/dap-extension/vscode/webfreak.debug/extension/out/src/backend/mi2/mi2.js:282:18)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

and *dap-debug* fails with the default configuration
```
  Warning (emacs): Initialize request failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
     at new NodeError (internal/errors.js:322:7)
     at validateString (internal/validators.js:124:11)
     at Object.isAbsolute (path.js:1133:5)
     at MI2.load (/home/user/.emacs.d/.local/etc/dap-extension/vscode/webfreak.debug/extension/out/src/backend/mi2/mi2.js:66:25)
     at GDBDebugSession.launchRequest (/home/user/.emacs.d/.local/etc/dap-extension/vscode/webfreak.debug/extension/out/src/gdb.js:67:29)
     at GDBDebugSession.dispatchRequest (/home/user/.emacs.d/.local/etc/dap-extension/vscode/webfreak.debug/extension/node_modules/vscode-debugadapter/lib/debugSession.js:366:22)
     at GDBDebugSession.handleMessage (/home/user/.emacs.d/.local/etc/dap-extension/vscode/webfreak.debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:61:18)
     at GDBDebugSession._handleData (/home/user/.emacs.d/.local/etc/dap-extension/vscode/webfreak.debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:155:34)
     at Socket.<anonymous> (/home/user/.emacs.d/.local/etc/dap-extension/vscode/webfreak.debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:80:44)
     at Socket.emit (events.js:400:28)

Debug session process exited with status: killed
```

**Comment by yyoncho** [comment]
Most likely delated to the discussion at  https://github.com/emacs-lsp/dap-mode/pull/529

**Comment by bbigras** [comment]
Should this be fixed since the PR was reverted?

**Comment by lucasmyers97** [comment]
I am also having this problem, even though I just recently copied the latest version of the repo into the melpa package location on my machine. Any tips on resolving it?

**Comment by mrOwner** [comment]
I have the same problem with dlv for golang

**Comment by davidhaley** [comment]
Similar error running dap-gdb-lldb. Output of trace:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  #<subr make-process>(:name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t)
  apply(#<subr make-process> (:name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t))
  make-process@with-editor-process-filter(#<subr make-process> :name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t)
  apply(make-process@with-editor-process-filter #<subr make-process> (:name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t))
  make-process(:name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t)
  apply(make-process (:name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t))
  dap--create-session((:type "gdb" :request "launch" :name "GDB::Run" :target "/myproject/myprogram" :cwd "myproject/" :dap-server-path "/usr/bin/gdb" :valuesFormatting "prettyPrinters"))
  dap-start-debugging-noexpand((:type "gdb" :request "launch" :name "GDB::Run" :target "/myproject/myprogram" :cwd "myproject/" :dap-server-path "/usr/bin/gdb" :valuesFormatting "prettyPrinters"))
  #f(compiled-function () #<bytecode -0x19fd771d9bdbe180>)()
  dap-debug((:type "gdb" :request "launch" :name "GDB::Run" :target nil :cwd nil))
  funcall-interactively(dap-debug (:type "gdb" :request "launch" :name "GDB::Run" :target nil :cwd nil))
  command-execute(dap-debug)
```

```
    Package: dap-mode
     Source: Straight
     Pinned: 496dd3a60f71a396df7e9a5ff6c500127d00ec03
      Build: HEAD -> master, replaced, origin/master 496dd3a 2024-07-22 16:47:46 -0700
             Build location: ~/.config/emacs/.local/straight/build-29.4/dap-mode/
             Repo location: ~/.config/emacs/.local/straight/repos/dap-mode/
     Recipe: (:type git :flavor melpa :files
              (:defaults "icons" "dap-mode-pkg.el")
              :host github :repo "emacs-lsp/dap-mode" :package "dap-mode" :local-repo "dap-mode")
                Homepage: https://github.com/emacs-lsp/dap-mode
    Modules: Declared by the following Doom modules:
             :tools debugger (readme)
    Configs: This package is configured in the following locations:
             modules/tools/debugger/config.el:112:(use-package! dap-mode
```

**Comment by davidhaley** [comment]
> Similar error running dap-gdb-lldb. Output of trace:
> 
> ```
> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>   #<subr make-process>(:name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t)
>   apply(#<subr make-process> (:name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t))
>   make-process@with-editor-process-filter(#<subr make-process> :name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t)
>   apply(make-process@with-editor-process-filter #<subr make-process> (:name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t))
>   make-process(:name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t)
>   apply(make-process (:name "GDB::Run" :connection-type pipe :coding no-conversion :command "/usr/bin/gdb" :stderr "*GDB::Run stderr*" :noquery t))
>   dap--create-session((:type "gdb" :request "launch" :name "GDB::Run" :target "/myproject/myprogram" :cwd "myproject/" :dap-server-path "/usr/bin/gdb" :valuesFormatting "prettyPrinters"))
>   dap-start-debugging-noexpand((:type "gdb" :request "launch" :name "GDB::Run" :target "/myproject/myprogram" :cwd "myproject/" :dap-server-path "/usr/bin/gdb" :valuesFormatting "prettyPrinters"))
>   #f(compiled-function () #<bytecode -0x19fd771d9bdbe180>)()
>   dap-debug((:type "gdb" :request "launch" :name "GDB::Run" :target nil :cwd nil))
>   funcall-interactively(dap-debug (:type "gdb" :request "launch" :name "GDB::Run" :target nil :cwd nil))
>   command-execute(dap-debug)
> ```
> 
> ```
>     Package: dap-mode
>      Source: Straight
>      Pinned: 496dd3a60f71a396df7e9a5ff6c500127d00ec03
>       Build: HEAD -> master, replaced, origin/master 496dd3a 2024-07-22 16:47:46 -0700
>              Build location: ~/.config/emacs/.local/straight/build-29.4/dap-mode/
>              Repo location: ~/.config/emacs/.local/straight/repos/dap-mode/
>      Recipe: (:type git :flavor melpa :files
>               (:defaults "icons" "dap-mode-pkg.el")
>               :host github :repo "emacs-lsp/dap-mode" :package "dap-mode" :local-repo "dap-mode")
>                 Homepage: https://github.com/emacs-lsp/dap-mode
>     Modules: Declared by the following Doom modules:
>              :tools debugger (readme)
>     Configs: This package is configured in the following locations:
>              modules/tools/debugger/config.el:112:(use-package! dap-mode
> ```

I decided to switch to `dap-gdb` instead of `dap-lldb`. `dap-lldb`.

Leaving this here in case it helps someone else:
```
(setq dap-gdb-lldb-path nil)
(setq dap-gdb-lldb-path-lldb nil)
(setq dap-gdb-lldb-download-url nil)
(setq dap-gdb-lldb-debug-program nil)
(setq dap-gdb-lldb-extension-version nil)

;; ensure dap-gdb-lldb is not loaded
(setq dap-auto-configure-mode nil)
(advice-add 'dap-gdb-lldb-setup :override #'ignore)

(use-package! dap-mode
    :defer t
    :config
    (require 'dap-gdb)

    (setq dap-auto-configure-features '(sessions locals controls tooltip))
    (setq dap-auto-show-output nil)
    (setq dap-gdb-debug-program '("gdb" "-i=dap"))

    (defun my/gdb-debug ()
        (interactive)
        (dap-debug
            (list :type "gdb"
                :request "launch"
                :name "GDB::Run"
                :program (read-file-name "Select executable to debug: ")
                :cwd default-directory)))

    (map! :leader
        :desc "dap debug (GDB)"   "D G" #'my/gdb-debug))

;; use add-hook! to ensure our configuration runs after dap-mode is loaded
(add-hook! 'dap-mode-hook
    (defun setup-dap-gdb ()
        ;; Clear all existing debug providers
        (clrhash dap--debug-providers)
        ;; Register and set our desired GDB providers
        (dap-register-debug-provider "gdb" #'dap-gdb--populate-gdb)
        (dap-register-debug-provider "gdbserver" #'dap-gdb--populate-gdbserver)))

;; force immediate setup if dap-mode is already loaded
(when (featurep 'dap-mode)
    (setup-dap-gdb))
```

For this example, I open a file in my project, add a breakpoint, and then execute `<leader> D G` and select the executable.
