### ISSUE TITLE
flutter run  --machine --start-paused --target lib/main.dart failed.

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/dap-mode#499]
Hi, i test dap-mode both an ruby and dart-mode, both of them get similiar error.

```
(node:269126) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

I create a issue https://github.com/emacs-lsp/lsp-dart/issues/117 too, and discuss there for some days.

i consider this is not a my own elisp config issue anyway, because i can reproduce it use minimum config for both dart and ruby,  individually.

## reproduce

environment:

Arch linux + self compiled emacs 27.2 with  janson JSON support 

nodejs, downloaded from https://nodejs.org/en/download/, use  Latest LTS Version: 14.17.5 

elisp config:

```cl
(require 'lsp-mode)
(require 'lsp-modeline)
(require 'lsp-headerline)
(require 'dap-mode)

(dap-mode 1)

(require 'dap-ui)
(dap-ui-mode 1)

(require 'dap-mouse)

(dap-tooltip-mode 1)

(require 'dap-ruby)
(dap-ruby-setup)

```

### 2. M-x  lsp, lsp get start successful, without error. (except tips unable autoconfigure company-mode)

![image](https://user-images.githubusercontent.com/549126/131211774-be85a947-db6a-4000-a129-c1b03fa09a78.png)

### 3. M-x dap-debug, select Ruby Run Configuration

Get following error (it same as when test with lsp-dart)

```
(node:274178) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Process Ruby::Run stderr finished
```

**Comment by yyoncho** [comment]
You should be using a different node version, but I am not sure which one.

**Comment by zw963** [comment]
> You should be using a different node version, but I am not sure which one.

Okay, can i know which version you used for develop ruby dap ?

**Comment by ericdallo** [comment]
I use node `12.22.5`

**Comment by zw963** [comment]
> I use node `12.22.5`

Wired, i use exact same version as you, but still get same issue

Following is error message from `*Flutter :: Debug stderr*` buffer. 

```
(node:117150) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Process Flutter :: Debug stderr finished
```

**Comment by zw963** [comment]
I expact describe my config and my process again.

### 1. use following config + Emacs 27.2

```cl
(require 'lsp-modeline)
(require 'lsp-headerline)
(require 'dap-mode)
(require 'dap-ui)
(require 'dap-mouse)
(require 'lsp-dart)
(require 'dart-mode)
(add-to-list 'auto-mode-alist '("\\.dart\\'" . dart-mode))
```

2.  in a dart project folder, use emacs with above config open lib/main.dart

```
$:  cd ~/Dart/app
$: emacs lib/main.dart
```

### run M-x lsp, successful.

### cursor on the line 4, then run `dap-debug`

![image](https://user-images.githubusercontent.com/549126/131225790-439152a7-148d-42a7-8e8e-d1e085e38989.png)

### Select Flutter :: Debug template

### Select browser as device

### Always get same error on  Flutter :: debug error.

**Comment by ericdallo** [comment]
@zw963 released a new lsp-dart 1.20.0 version which improves the log output, maybe it can help with your debug

**Comment by zw963** [comment]
> @zw963 released a new lsp-dart 1.20.0 version which improves the log output, maybe it can help with your debug

Thank you very much for we have feature like `lsp-log-io` in dap.

Following is the output of error come from `*Flutter :: Debug out*

```
Spawning /home/zw963/Dropbox/linux/utils/flutter/bin/flutter with args ["run","--machine","--start-paused","--target","lib/main.dart"]..  in /home/zw963/Dart/myapp/    PID: 182228More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
Linux (desktop) • linux  • linux-x64      • Linux
Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159
Process terminated! 1, null
```

Following is message come from `*LSP Dart - Flutter daemon*`.

```
[{"event":"daemon.connected","params":{"version":"0.6.0","pid":181684}}]
[{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[{"id":28516}]
[{"event":"device.added","params":{"id":"linux","name":"Linux","platform":"linux-x64","emulator":false,"category":"desktop","platformType":"linux","ephemeral":false,"emulatorId":null}}]
[{"event":"device.added","params":{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null}}]
[{"id":12646,"result":[{"id":"mate20pro","name":"mate20pro","category":"mobile","platformType":"android"}]}]
```

--------------

Some context:

### 1. i test this feature on a new created project with `flutter create myapp` use latest flutter stable 

```sh
 ╰─ $ flutter --version
Flutter 2.2.3 • channel stable • https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
Framework • revision f4abaa0735 (8 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

### 2. after cd myapp folder, i can always run `flutter run -d chrome` successful.

it open a chrome window like this:

![image](https://user-images.githubusercontent.com/549126/131239152-421aa86b-7174-4731-bfbc-d77178bac9bb.png)


### 3. But i can't run it successful use following command as debug message output.

```sh
 ╰─ $ flutter run  --machine --start-paused --target lib/main.dart
Multiple devices found:
Linux (desktop) • linux  • linux-x64      • Linux
Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 2
[{"event":"daemon.connected","params":{"version":"0.6.0","pid":184291}}]

Oops; flutter has exited unexpectedly: "Bad state: Stream has already been listened to.".
A crash report has been written to /home/zw963/Dart/myapp/flutter_03.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+Bad+state%3A+Stream+has+already+been+listened+to.

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JEoH7
```

**Comment by ericdallo** [comment]
Yeah, that seems to be a issue on flutter itself @zw963 :/

**Comment by zw963** [comment]
> Yeah, that seems to be a issue on flutter itself @zw963 :/


I use a stable release flutter, can you please test this new create app on your's local ?

[myapp.tar.gz](https://github.com/emacs-lsp/dap-mode/files/7072696/myapp.tar.gz)

**Comment by zw963** [comment]
@ericdallo , i check options, there is no `--machine` option exists.

```sh
╰─ $ flutter run --help |grep machine

 ╭─ 22:47  zw963 ⮀ ~/Dart/myapp ⮀ ➦ ruby-3.0.2  0 
 ╰─ $ 1  
```

And if remove it,  i guess flutter run start successful.

```sh
 ╰─ $ flutter run --start-paused --target lib/main.dart
Multiple devices found:
Linux (desktop) • linux  • linux-x64      • Linux
Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 2
Launching lib/main.dart on Chrome in debug mode...

Waiting for connection from debug service on Chrome...             16.5s
This app is linked to the debug service: ws://127.0.0.1:45619/-2PFyNq3PAw=/ws
Debug service listening on ws://127.0.0.1:45619/-2PFyNq3PAw=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

```

In fact, --target is unnecessary too.

```
 ╰─ $ 2  flutter run --help |grep -e --target
-t, --target=<path>                               The main entry-point file of the application, as run on the device.
                                                  If the "--target" option is omitted, but a file name is provided on the command line, then that is used instead.
```

i can run success with this command:

``flutter run --start-paused lib/main.dart``

**Comment by ericdallo** [comment]
@zw963 --machine exists and it's used to send/receive json, meant to be used by process not interactively.
--target is added by the debugger itself, in this case Dart-Code repository that host the debugger

**Comment by zw963** [comment]
> @zw963 --machine exists and it's used to send/receive json, meant to be used by process not interactively.
> --target is added by the debugger itself, in this case Dart-Code repository that host the debugger

Okay, following is the log, you think i should report it on flutter official repo, right?

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --start-paused --target lib/main.dart

## exception

StateError: Bad state: Stream has already been listened to.

```
#0      _StreamController._subscribe (dart:async/stream_controller.dart:635:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
#3      _Socket.listen (dart:io-patch/socket_patch.dart:2020:31)
#4      _StdStream.listen (dart:io/stdio.dart:22:20)
#5      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:49:16)
#6      _BoundSinkStream.listen (dart:async/stream_transformers.dart:171:9)
#7      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:49:16)
#8      _BoundSinkStream.listen (dart:async/stream_transformers.dart:171:9)
#9      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#10     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#11     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#12     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#13     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#14     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#15     new Daemon (package:flutter_tools/src/commands/daemon.dart:88:42)
#16     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:534:29)
<asynchronous suspension>
#17     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#23     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/zw963/Dropbox/linux/utils/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/zw963/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/zw963/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.1
    • cmake version 3.21.2
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

**Comment by ericdallo** [comment]
Exactly, IMO that should be enough to they understand the issue

**Comment by zw963** [comment]
Okay, i report there.

https://github.com/flutter/flutter/issues/89132

**Comment by zw963** [comment]
Fixed possible because dap client version too old, see https://github.com/emacs-lsp/lsp-dart/issues/117
