### ISSUE TITLE
dap-firefox, dap-firefox-setup, extension/module is extracted but no script file 

### ISSUE THREAD

**Issue by Inc0n** [emacs-lsp/dap-mode#547]
The error log is as follow, in `*Firefox::Run stderr*`
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/xception/.emacs.d/var/dap/extensions/vscode/firefox-devtools.vscode-firefox-debug/extension/out/firefoxDebugAdapter.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.0.1

Process Firefox::Run stderr finished
```

emacs version: 28
dap-mode version: 20211117.1555

**Comment by billop** [comment]
I am experiencing almost the same issue with `dap-node`:
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/x/.local/share/emacs/dap/extensions/vscode/ms-vscode.node-debug2/extension/out/src/nodeDebug.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Process Node::Run stderr finished
```

**Comment by rafiks** [comment]
similar issue here. 
not sure if its an issue within emacs or if the file changed.
I am going to try and see if I can manually download.


Contacting host: marketplace.visualstudio.com:443
Wrote /var/folders/r3/bxfgg2yn7_90v1vkj_y4_3740000gn/T/exttxsW6F.zip
[/var/folders/r3/bxfgg2yn7_90v1vkj_y4_3740000gn/T/exttxsW6F.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/r3/bxfgg2yn7_90v1vkj_y4_3740000gn/T/exttxsW6F.zip or
        /var/folders/r3/bxfgg2yn7_90v1vkj_y4_3740000gn/T/exttxsW6F.zip.zip, and cannot find /var/folders/r3/bxfgg2yn7_90v1vkj_y4_3740000gn/T/exttxsW6F.zip.ZIP, period.
dap-node: Downloading done!

**Comment by rafiks** [comment]
I was able to manually download and unpack on the folder. Still testing it out. On initial try, Node-debug and firefox did not launch. Chrome launch but it doesn't look like its configured properly.

**Comment by mplanchard** [comment]
I also ran into this for `dap-gdb-lldb`, for rust debugging. I was able to manually download the extension from https://marketplace.visualstudio.com/items?itemName=webfreak.debug and unpack it into the `dap-gdb-lldb-path` and get things working

**Comment by yyoncho** [comment]
The solution for now is to copy the extension here and download it from the repo: https://github.com/emacs-lsp/lsp-server-binaries/

**Comment by dylanjw** [comment]
@yyoncho Can you add more description to your proposed solution? Im not understanding.

**Comment by woochica** [comment]
Has anyone managed to get this solved?

**Comment by misieck** [comment]
+1 on _Originally posted by @woochica in https://github.com/emacs-lsp/dap-mode/issues/547#issuecomment-1419076149_
I may add, the same extension does work in vscode. Did the extension api change?

**Comment by cpol0** [comment]
Same problem here. I've rebuild the firefox extension https://github.com/firefox-devtools/vscode-firefox-debug 2.9.7 version and rollback until 2.9.4 (2 years ago) with the `package` command, there is absolutely no `https://github.com/firefox-devtools/vscode-firefox-debug.js` file.
So it seem's to be broken since a very long time, did anyone try this extension successfuly recently?

Unfortunately, the alternative with dap-chrome (deprecated) seems not working too https://github.com/emacs-lsp/dap-mode/issues/369

**Comment by nailuoGG** [comment]
I'm encountering the same issue. After analysis, we found that the plugin is downloaded from the following URL when calling the dap-xxx-setup:

```
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/%s/vsextensions/%s/%s/vspackage
```

The code for this can be found here:
https://github.com/emacs-lsp/dap-mode/blob/374fd0511ef5349f7621c15f5ce2e22f307f6e68/dap-utils.el#L57-L61

For instance, when running the command dap-firefox-setup, the download URL is as follows:

```
curl https://marketplace.visualstudio.com/_apis/public/gallery/publishers/firefox-devtools/vsextensions/vscode-firefox-debug/latest/vspackage
```

However, downloading from the above URL results in an error, and we must explicitly specify a version and cannot use 'latest', as shown below:

```
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/firefox-devtools/vsextensions/vscode-firefox-debug/2.9.8/vspackage
```

The reason for this could be that no plugin version is passed in any dap-xxx-setup, and the api no longer supports downloading extension files using the latest version.

https://github.com/emacs-lsp/dap-mode/blob/374fd0511ef5349f7621c15f5ce2e22f307f6e68/dap-firefox.el#L46-L47

Solution: 
When there is no version passed, `dap-utils-get-vscode-extension` should query the latest version from the marketplace:

```
https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
```

**Comment by woochica** [comment]
@nailuoGG for me pulling the latest version works well:

`curl https://marketplace.visualstudio.com/_apis/public/gallery/publishers/firefox-devtools/vsextensions/vscode-firefox-debug/latest/vspackage --output `

but the problem is that, regardless which version you fetch, none of them contain the `firefoxDebugAdapter.js`.

**Comment by lrdass** [comment]
Has anyone found the solution? none of the `.vsix` packages has the expected `firefoxDebugAdapter.js` in it

**Comment by tillydray** [comment]
There's got to be a better way, but this is what I had to do to get it working

## With Firefox

1. Navigate to https://marketplace.visualstudio.com/items?itemName`firefox-devtools.vscode-firefox-debug
2. Click Download Extension
3. extract `adapter.bundle.js`, `mappings.wasm`, and `launcher.bundle.js` into `~/.emacs.d/.local/etc/dap-extension/vscode/firefox-devtools.vscode-firefox-debug/extension/out/`
4. `(require 'dap-firefox)`
5. `(dap-firefox-setup)` probably isn't required here if all it does it try to download and install the files from step 3 above
6. `(dap-debug)`

## With Brave
1. `(require 'dap-chrome)`
2. `(dap-chrome-setup)`
3. set `"runtimeExecutable": "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",` in `<project_root>/.vscode/launch.json` to use Brave instead of Chrome
4. `(dap-debug)`

If you don't mind using Chrome of course don't do step 3

Note: I spent some time writing this comment and at some point `dap-debug` worked for me using Brave, but now it isn't and I don't think anything changed. I'm getting `Error: Cannot find module '~/.emacs.d/.local/etc/dap-extension/vscode/msjsdiag.debugger-for-chrome/extension/out/src/chromeDebug.js'`

## `launch.json`

Here's the contents of my `launch.json` in case that's helpful

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Firefox",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "sourceMaps": true,
            "file": "${workspaceFolder}/index.html",
            "log": {
                "fileName": "${workspaceFolder}/log.txt",
                "fileLevel": { "default": "Debug" }
            }
        },
        {
            "name": "Node",
            "type": "node",
            "request": "launch",
            "reAttach": true,
            "sourceMaps": true,
            "file": "${workspaceFolder}/src/gameLogic.test.ts",
            "log": {
                "fileName": "${workspaceFolder}/log.txt",
                "fileLevel": { "default": "Debug" }
            }
        },
        {
            "name": "Chrome",
            "type": "chrome",
            "mode": "url",
            "runtimeExecutable": "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
            "request": "launch",
            "reAttach": true,
            "sourceMaps": true,
            "url": "http://localhost:8080",
            "log": {
                "fileName": "${workspaceFolder}/log.txt",
                "fileLevel": { "default": "Debug" }
            }
        }
    ]
}

```
