### ISSUE TITLE
Debugpy doesn't work at all

### ISSUE THREAD

**Issue by NovaViper** [emacs-lsp/dap-mode#575]
Hey I have debugpy setup for the Python debugger but it refuses to work, I have a simple `output = input(Hello World)` command in my py file but I get this error in the buffer

```
Hello thereTraceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/usr/lib/python3.10/site-packages/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/usr/lib/python3.10/site-packages/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/novaviper/Documents/Projects/Labs/Python/test.py", line 8, in <module>
    out = input("Hello there")
EOFError: EOF when reading a line
```

How do I make it go away? I don't have this issue when I use pvstd

**Comment by DJManas** [comment]
I am wondering, does it let you to enter the value for input command? I had tried it, but even in ptvsd it doesn't throw exception, but won't let me to enter the value and thus the program not continuing.

**Comment by DJManas** [comment]
Oh I see. I was testing it under spacemacs, and it just froze and I could not enter anything so I searched how to use vterm as the launch terminal, but was unsuccesfull. In doom it crashes right away, but I was thinking about taking a look at it and I failed to find it.

I had also searched the internet and I had found, that some things were mentioned in connection to VSCode, so i am not perfectly sure if its not related to some [backend](https://github.com/microsoft/debugpy/issues/370) process than to dap-mode, but I don't know. Maybee pasting this paragraph for someone who would be able to resolve this issue.

**Comment by NovaViper** [comment]
@DJManas Well, I can't send the issue over in debugpy's github since the backend issue already seems to be fixed in a patch it seems

**Comment by simurgh9** [comment]
Ran into the same issue.
