### ISSUE TITLE
Exception in ptvsd when encountering a breakpoint i Python program

### ISSUE THREAD

**Issue by thermopyle** [emacs-lsp/dap-mode#636]
I'm trying to debug a Python program using dap-mode and ptvsd. If I run the program in the dap-mode debugger without any breakpoints, all works fine. But when I add a breakpoint (using dap-hydra) to the Python program, an exception is thrown when the breakpoint is hit. The following stack is shown in the *<program name>  server log* buffer;
```
Traceback (most recent call last):
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 283, in _on_run
    self.process_net_command_json(self.global_debugger_holder.global_dbg, json_contents)
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 164, in process_net_command_json
    cmd = on_request(py_db, request)
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 623, in on_stacktrace_request
    self.api.request_stack(py_db, request.seq, thread_id, fmt=fmt, start_frame=start_frame, levels=levels)
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 190, in request_stack
    if internal_get_thread_stack.can_be_executed_by(get_current_thread_id(threading.current_thread())):
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 595, in can_be_executed_by
    self._cmd = py_db.cmd_factory.make_get_thread_stack_message(
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py", line 238, in make_get_thread_stack_message
    end = min(start + levels, total_frames)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
dap-mode version: dap-mode-20220612.1850
ptvsd version: 4.3.2
Python version: 3.9.13
Emacs version: 29.0.50
OS: macOS Monterey

dap-mode config:
```
(use-package dap-mode
  :if (eq system-type 'darwin)
  :ensure t
  :bind
  (:map global-map
	("C-c d" . dap-hydra)
	("C-c r" . dap-ui-repl))
  :hook
  (dap-stopped . (lambda (arg) (call-interactively #'dap-hydra)))
  :config
  (use-package dap-lldb
    :config
    (setq dap-lldb-debug-program '("/opt/homebrew/opt/llvm/bin/lldb-vscode")))
  (use-package dap-python)
  (setq dap-ui-variable-length 200)
  (setq dap-inhibit-io nil)
  (setq dap-print-io t)
  (dap-auto-configure-mode)
  (dap-register-debug-template "Cleanup"
			       (list :type "python"
				     :args ""
				     :cwd "/Users/mikael/Develop/buildsystem/bootstrap"
				     :target-module "/Users/mikael/Develop/buildsystem/bootstrap/cleanup.py"
				     :request "launch"
				     :name "cleanup.py")))
```

**Comment by yyoncho** [comment]
ptvsd is deprecated, please switch to debugpy.

**Comment by thermopyle** [comment]
I changed to using debugpy instead, strangely enough I get the same error:

```
Traceback (most recent call last):
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 251, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 194, in process_net_command_json
    cmd = on_request(py_db, request)
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 950, in on_stacktrace_request
    self.api.request_stack(py_db, request.seq, thread_id, fmt=fmt, start_frame=start_frame, levels=levels)
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 205, in request_stack
    if internal_get_thread_stack.can_be_executed_by(get_current_thread_id(threading.current_thread())):
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 653, in can_be_executed_by
    self._cmd = py_db.cmd_factory.make_get_thread_stack_message(
  File "/Users/mikael/Develop/.virtualenvs/pyvenv3.9/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py", line 281, in make_get_thread_stack_message
    end = min(start + levels, total_frames)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

```

**Comment by yyoncho** [comment]
For that error we know the solution: https://github.com/emacs-lsp/dap-mode/issues/625#issuecomment-1141082447

**Comment by thermopyle** [comment]
I installed debugpy using `pip install git+https://github.com/microsoft/debugpy.git@78b030f5092d91df64860914962333e89852ea9b`, that fixed the problem, it works now.
