### ISSUE TITLE
dap-gdb-lldb-debug-program is not correct.

### ISSUE THREAD

**Issue by yssource** [emacs-lsp/dap-mode#69]
I am using https://github.com/WebFreak001/code-debug for debugging c++.

- `ext install webfreak.debug` in vscode
The gdb.js is located in /home/jimmy/.vscode-oss/extensions/webfreak.debug-0.23.1/out/src/gdb.js

- `mkdir -v ~/.extensions && ln -s /home/jimmy/.vscode-oss/extensions/webfreak.debug-0.23.1 ~/.extensions/webfreak.debug`

https://github.com/emacs-lsp/dap-mode/blob/944fb6b0832aa36be5ebb29b74126afefee6fecb/dap-gdb-lldb.el#L37

I think it is supposed to be "**out/src/gdb.js**", instead of "extension/out/src/gdb.js", isn't it?

**Comment by yssource** [comment]
``` bash
Error: Cannot find module '/home/jimmy/.extensions/webfreak.debug/extension/out/src/gdb.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Process GDB::Run stderr finished

```

**Comment by yssource** [comment]
it happens to lldb also.


``` bash
Error: Cannot find module '/home/jimmy/.extensions/webfreak.debug/extension/out/src/lldb.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Process LLDB::Run stderr finished

```

**Comment by yyoncho** [comment]
Note that the path has extension version and it will change when a new version of native debug is released. Thus I cannot have a constant path which always works but the users of the extension have to adjust it. Also, not everyone is using vscode to download the extension, I personally download the extension directly from marketplace. But if you think that there is a better default path feel free to provide a PR. We might implement automatic download of the extension from market place but this won't happen anytime soon.
