### ISSUE TITLE
cannot provide input from console interactively python debugging

### ISSUE THREAD

**Issue by nthainguyen** [emacs-lsp/dap-mode#97]
I would like to debug a small script which require input from user, however I cannot type in the console when the prompt appears.

I can totally debug this using VScode. I have yet found a way to do the same in emacs dap mode.

**Comment by yyoncho** [comment]
Do ```(setq dap-python-executable "xterm -e python")``` which will start the python debug process in an external terminal which does have stdin. `xterm -e` stands for "start xterm and execute the command".

**Comment by nbfalcon** [comment]
As of now:
```emacs-lisp
(setq dap-python-debugger 'debugpy)
```

Then add :console "internal" to your debug conf.

**Comment by leanid** [comment]
> As of now:
> 
> ```emacs-lisp
> (setq dap-python-debugger 'debugpy)
> ```
> 
> Then add :console "internal" to your debug conf.

What is `:console "internal"` where can I find debug conf? I use doom-emacs and just try to debug simple file like:

    #!/usr/bin/env python3

    print("Hello World")
    user_name = input("your name is: ")
    print(f"Hello {user_name}")

After I set in ~/.doom.d/config.el:

    (after! dap-mode
      (setq dap-python-debugger 'debugpy))

I see exception on start dap-debug:

    Hello World
    your name is: Traceback (most recent call last):
      File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/home/l_chayka/.local/lib/python3.10/site-packages/debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
        cli.main()
      File "/home/l_chayka/.local/lib/python3.10/site-packages/debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
        run()
      File "/home/l_chayka/.local/lib/python3.10/site-packages/debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
        runpy.run_path(target, run_name="__main__")
      File "/home/l_chayka/.local/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
        return _run_module_code(code, init_globals, run_name,
      File "/home/l_chayka/.local/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/home/l_chayka/.local/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
        exec(code, run_globals)
      File "/home/l_chayka/fun/test/hello.py", line 4, in <module>
        user_name = input("your name is: ")
    EOFError: EOF when reading a line
